### PR TITLE
superhero and doge

### PR DESCRIPTION
**Pull request by rahulkumaran**
https://codepen.io/rahulkumaran/pen/aqJgKO ---- superhero
https://codepen.io/rahulkumaran/pen/wyJLOx ---- doge
superhero #59 
doge #15

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
Thanx but no PR's to be merged now 😄

**Comment by Anupam-dagar** [comment]
you can send the PR for this as a contributor after 4-5 days.

**Comment by rahulkumaran** [comment]
won't it be considered now? @Anupam-dagar  :(

**Comment by Anupam-dagar** [comment]
@rahulkumaran sorry but time is over.PR's only for updating scores will be considered.

**Pull request closed without merging**
