### PR TITLE
Pure CSS image of Doge Added

### PR DESCRIPTION
**Pull request by nikki1016**
[link](https://codepen.io/nikki1016/pen/OzwBVO)

### CODE REVIEW

**Comment by gauthamzz** [comment]
Comment link https://codepen.io/nikki1016/pen/OzwBVO like this in description of pr

**Comment by gauthamzz** [comment]
and thats a dog , not a doge 🐶

**Comment by gauthamzz** [comment]
image
This magnificant creature is a DOGE

**Comment by gauthamzz** [comment]
@mubaris if you are okay with it, merge it 😄

**Comment by mubaris** [comment]
whatever. merge it

**Review by mubaris — APPROVED** [review]

**Comment by gauthamzz** [comment]
The internet needed a pure CSS doge. I just wanted to show de wey 😄

**Comment by gauthamzz** [comment]
anyway good job @nikki1016

**Comment by nikki1016** [comment]
i thought that's normal dog emoji as mentioned in the description previously...not noticed that 'e'

**Pull request merged**
