### PR TITLE
adding wine glass

### PR DESCRIPTION
**Pull request by ananya**
issue number #10 
link: https://codepen.io/ananya-agrawal/pen/LeaxLw?editors=1100

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
resolve conflicts, also the wine brown color is not coming inside glass properly, fix it

**Comment by ananya** [comment]
@Anupam-dagar pls check it now

**Comment by gauthamzz** [comment]
The wine Is outside the glass , fix it

**Comment by ananya** [comment]
how could this be fixed?

**Comment by gauthamzz** [comment]
google it :)

**Comment by ananya** [comment]
gl
i m not getting why is this looking out of the glass

**Comment by gauthamzz** [comment]
deepinscreenshot_select-area_20180122231318

Its not responsive, use your broswer change its size. you will see the magic 🌟

**Comment by ananya** [comment]
check it now!!
https://codepen.io/ananya-agrawal/pen/LeaxLw?editors=1100

**Comment by Anupam-dagar** [comment]
LGTM :+1:

**Pull request merged**
