### PR TITLE
created a pure css cat and added snowman

### PR DESCRIPTION
**Pull request by rudransh1**
issue #24 
issue #38

### CODE REVIEW

**Comment by rudransh1** [comment]
cat: https://codepen.io/hacker1x1x1/pen/WMeNRB
snowman: https://codepen.io/hacker1x1x1/pen/JMgXbd
@gauthamzz

**Review by gauthamzz — APPROVED** [review]
Looks good

**Comment by gauthamzz** [comment]
Fix conflicts

**Comment by rudransh1** [comment]
resolved @gauthamzz

**Pull request merged**
