### PR TITLE
Add isometric design

### PR DESCRIPTION
**Pull request by ekanban**
issue #60 

[https://codepen.io/Ace-Bansal/full/vpqyVR/](https://codepen.io/Ace-Bansal/full/vpqyVR/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
you need to make it bigger, its incomplete. Take more time. it has more points.

**Comment by ekanban** [comment]
@gauthamzz Alright 😀

**Comment by gauthamzz** [comment]
I’ll close this if not finished within 12 hours

**Comment by ekanban** [comment]
@gauthamzz I'm working on it. Will be submitting the changes soon.

**Comment by ekanban** [comment]
@gauthamzz Please have a look. Hope you like it now!
[https://codepen.io/Ace-Bansal/full/vpqyVR/](https://codepen.io/Ace-Bansal/full/vpqyVR/)

**Review by gauthamzz — APPROVED** [review]

**Comment by Ace-Bansal** [comment]
@gauthamzz Resolved conflicts.

**Review by gauthamzz — APPROVED** [review]

**Pull request merged**
