### PR TITLE
Concept 1 Login UI , Wine Glass,Pure CSS Cat and Pure CSS Doge

### PR DESCRIPTION
**Pull request by aadixiiita**
issue no. #11 
issue no. #5 
issue no. #6 
issue no. #24 

codepen Link for Login UI - https://codepen.io/aadixiiita/pen/OzKyOY

codepen link for Wine Glass - https://codepen.io/aadixiiita/pen/ppMbRJ

codepen link for Doge Css - https://codepen.io/aadixiiita/pen/ZvgJxo?editors=0100#0

codepen link for Cat Css - https://codepen.io/aadixiiita/pen/EoqEVg

### CODE REVIEW

**Comment by gauthamzz** [comment]
Login ui is not correct , read the issue properly

**Comment by aadixiiita** [comment]
@gauthamzz Fixed the Login UI

**Comment by gauthamzz** [comment]
its not good,make it better.

**Comment by aadixiiita** [comment]
@gauthamzz  changes done , review it.

**Pull request merged**
