### PR TITLE
created a login page

### PR DESCRIPTION
**Pull request by rudransh1**
issue #11

### CODE REVIEW

**Comment by gauthamzz** [comment]
doesnt look good. improve design.

**Comment by rudransh1** [comment]
review it now @gauthamzz 
https://codepen.io/hacker1x1x1/pen/VyqpjQ

**Comment by gauthamzz** [comment]
It’s not size of mobile screen and it won’t look good in mobile .try something

**Comment by rudransh1** [comment]
have a look now @gauthamzz 
https://codepen.io/hacker1x1x1/pen/VyqpjQ

**Pull request merged**
