### PR TITLE
Add login UI

### PR DESCRIPTION
**Pull request by druvalcr28**
created login page #11 

Live Link : https://codepen.io/Druv/pen/rpoogw

### CODE REVIEW

**Comment by gauthamzz** [comment]
make better bg card

**Comment by gauthamzz** [comment]
Make changes by Tommorow night or I’ll close this pr

**Comment by druvalcr28** [comment]
@gauthamzz background is updated

**Comment by gauthamzz** [comment]
@druvalcr28 fix the merge confilcts ,it looks good

**Pull request closed without merging**
