### PR TITLE
Add Login page and Cat.

### PR DESCRIPTION
**Pull request by ekanban**
issue #11 and #24 

[Login page](https://codepen.io/Ace-Bansal/full/BYpMdp/)
[Cat](https://codepen.io/Ace-Bansal/full/WMpdzb/)

### CODE REVIEW

**Comment by ekanban** [comment]
@gauthamzz Kindly review.

**Review by Anupam-dagar — CHANGES_REQUESTED** [review]
@Ace-Bansal please rename the pen to OpenCode - Login UI and similarly for cat.Also in login form password field should have type="password"

**Comment by ekanban** [comment]
On it

**Comment by gauthamzz** [comment]
Fix merge conflicts

**Comment by ekanban** [comment]
@Anupam-dagar @gauthamzz done

**Review by gauthamzz — APPROVED** [review]

**Pull request merged**
