### PR TITLE
Added Arpit's design of a login page

### PR DESCRIPTION
**Pull request by arpitmisraw**
Issue - #11

### CODE REVIEW

**Comment by gauthamzz** [comment]
Give link

**Review by gauthamzz — APPROVED** [review]

**Comment by gauthamzz** [comment]
I still need link as comment

**Comment by arpitmisraw** [comment]
Sorry @gauthamzz . Here it is-
[Login Page](https://codepen.io/arpitmisraw/pen/rJyvqm)

**Comment by gauthamzz** [comment]
Looks weird make it better.

**Comment by arpitmisraw** [comment]
Could you tell me what you're looking for so that I can change that.

**Comment by gauthamzz** [comment]
Last few hours there is no point in asking , make anything fine I’ll
merge

**Comment by arpitmisraw** [comment]
@gauthamzz  I changed it a little bit. Please review.

**Pull request merged**
