### PR TITLE
Made a ProDesigner Website

### PR DESCRIPTION
**Pull request by arpitmisraw**
#72 

[link](https://arpitmisraw.github.io/ProDesigner/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
Link doesn’t work , didn’t pass the checks

**Comment by arpitmisraw** [comment]
It does now. Please check.

**Comment by gauthamzz** [comment]
Still checks not passing

**Comment by arpitmisraw** [comment]
I'll make the changes.

**Comment by arpitmisraw** [comment]
@gauthamzz I can't seem to solve the last issue. Can you help me?

**Pull request merged**
