### PR TITLE
Pure CSS Images Task 1 - Wine Glass

### PR DESCRIPTION
**Pull request by nikki1016**
issue no. #5

### CODE REVIEW

**Comment by gauthamzz** [comment]
Why is there a face on wine glass ?

**Comment by nikki1016** [comment]
just to make it more interesting..anyway it is DIY wine glass ..
should I modify it ?

**Comment by mubaris** [comment]
I think it's okay

**Review by mubaris — APPROVED** [review]

**Comment by gauthamzz** [comment]
when you scrolled it up,it felt like the face was coming off the wine glass. Seems like they are seprate parts or something.

anyway okay

**Comment by nikki1016** [comment]
I will remove that face part....It is my first pure CSS image

**Comment by gauthamzz** [comment]
nah its okay 😄

**Pull request merged**
