### PR TITLE
#6 Doge added

### PR DESCRIPTION
**Pull request by yashagarwal17**
https://codepen.io/yash-agarwal17/pen/dJgwyK

### CODE REVIEW

**Comment by gauthamzz** [comment]
You have a class named cat 🐈, explain

**Comment by yashagarwal17** [comment]
Actually i started making a cat.....but it turned out more to be a doge like......so i sumbit it under doge issue......srry i didn't pay attention to the class name

**Comment by gauthamzz** [comment]
It doesn’t look like a doge, make changes. Make it look like a doge

**Comment by gauthamzz** [comment]
Inactive thread

**Pull request closed without merging**
